### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by wxy-2012** [Matthew-Lyu/Autonomous-Driving-Simulation-ROS-Noetic#2]
![65a72aa0-396f-446a-b739-27f02b5aa463](https://github.com/user-attachments/assets/0ee35746-3066-47d9-8b81-88d99d234234)
I used the readme method and it worked, but it showed no map, what should I do?

**Comment by Matthew-Lyu** [comment]
You should check the Map option in the Displays of Rivz
<img width="310" alt="WechatIMG2254" src="https://github.com/user-attachments/assets/f810f9a8-87cc-4520-9556-fd471466886b">

**Comment by wxy-2012** [comment]
thank you for your help， I have successfully reproduction your code.



---Original---
From: "Weichen ***@***.***&gt;
Date: Tue, Nov 26, 2024 13:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Matthew-Lyu/Autonomous-Driving-Simulation-ROS-Noetic] somequestion (Issue #2)




 
Closed #2 as completed.

**Comment by Matthew-Lyu** [comment]
You are welcome！🥰
